version: '3.6'
services:
 web:
    build:
     context: ./
     dockerfile: Dockerfile
    container_name: php72
    depends_on:
      - db
    volumes:
      - /home/juselero/Escritorio/appswen:/var/www/html
    ports:
      - 8080:80  

 db:
    container_name: mysql8
    image: mysql:8.0.23
    
    restart: always
    volumes:
      - /home/juselero/Escritorio/appswen/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: xcocuy32@   
    ports:
      - 6033:3306
 
